
export const FORM_FIELD_COLOR = '#2596be';
export const TEXT_AREA_COLOR = 'bbb';
export const PRIMARY_COLOR = '#e0e4dd';
export const SECONDARY_COLOR = '#368382';
export const BACKGROUND_IMAGE = process.env.REACT_APP_BACKGROUND_IMAGE_URL;
export const BLACK = '#000000';
export const WHITE = '#ffffff';
export const BLUE = '#0000ff';
export const TRANSPARENT = 'transparent';
export const DRAWER_DETAILS_FONT_COLOR = 'gray.600';
export const CARD_BACKGROUND_COLOR = '#fffbf1';
export const GRAY = '#51515b';
export const FOOTER_BACKGROUND_COLOR ='#e0e4dd';
export const EVENT_TITLE_PADDING_COLOR = '#e0e4dd';
export const DRAWER_BACKGROUND_COLOR = '#fffaee';
export const BACKGROUND_COLOR = '#a1c4fd';
export const ABOUT_PAGE_BACKGROUND_COLOR = '#fffaee';
export const HEADER_BACKGROUND_COLOR = '#e0e4dd';
